#FROM ubuntu:16.04
#FROM ubuntu:18.04

# user name
ARG USER=foo

# packages to install
ARG PKGS=" \
	apt-file \
	autoconf \
	autopoint \
	bc \
	bison \
	build-essential \
	clang \
	cython \
	flex \
	gettext \
	git \
	gtk-doc-tools \
	libelf-dev \
	liblzma-dev \
	libssl-dev \
	libtool \
	nano \
	pkg-config \
	rsync \
	strace \
	sudo \
	texinfo \
	wget \
"

RUN \
	apt-get update && \
	# Suppress "delaying package configuration" warning
	DEBCONF_NOWARNINGS=yes apt-get install -y apt-utils && \
	# Install various packages
	apt-get install -y ${PKGS} && \
	# Add a normal privilege user
	useradd -m ${USER} && \
	# Allow the user to 'sudo' without password
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# login as a normal privilege user
USER ${USER}
WORKDIR /home/${USER}
