ARG FROM=centos
#ARG FROM=centos:6
#ARG FROM=centos:7

FROM ${FROM}

# packages to install
ARG PKGS=" \
	bison \
	clang \
	flex \
	gcc \
	git \
	make \
	nano \
	strace \
	sudo \
"

RUN \
	# Install manuals
	sed -i '/^tsflags=nodocs$/d' /etc/yum.conf && \
	yum update -y && \
	yum reinstall -y yum && \
	yum install -y man && \
	# Install various packages
	yum install -y ${PKGS}

COPY entrypoint /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint"]
