#FROM fedora:29

# user name
ARG USER=foo

# packages to install
ARG PKGS=" \
	bison \
	clang \
	flex \
	gcc \
	git \
	make \
	nano \
	strace \
"

RUN \
	# Uncomment the following three lines if you want to install manuals
	#sed -i '/^tsflags=nodocs$/d' /etc/yum.conf && \
	#yum reinstall -y yum && \
	#yum install -y man && \
	# Install various packages
	yum install -y ${PKGS} && \
	# Set the root password empty
	echo 'root:' | chpasswd && \
	# Add a normal privilege user
	useradd -m ${USER}

# login as a normal privilege user
USER ${USER}
WORKDIR /home/${USER}
