ARG FROM=archlinux

FROM ${FROM}

# user name
ARG USER=foo

RUN \
	sed -i '/NoExtract.*usr\/share\/man/s/^/#/' /etc/pacman.conf && \
	pacman -Sy --noconfirm \
		bison \
		flex \
		gcc \
		gettext \
		make \
		man \
		nano \
		pkg-config \
		sudo \
		&& \
	# Add a normal privilage user
	useradd -m ${USER} && \
	# Allow the user to 'sudo' without password
	echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# login as a normal privilege user
USER ${USER}
WORKDIR /home/${USER}
