#!/bin/sh

set -e

build_only=

while [ $# -gt 0 ]
do
	case "$1" in
	-b | --build-only) build_only=1;;
	-d | --debug) set -x;;
	-* | --*) echo "$1: unknown option" >&2; exit 1;;
	*) break;;
	esac
	shift
done

default=ubuntu
mount_dirs="ref tools"

# The base image used for 'FROM'
# e.g. ubuntu, ubuntu:18.04, fedora:latest, etc.
from=${1:-$default}

distro=${from%:*}

# the directory path where this script is located
this_dir=$(dirname $(realpath $0))

dockerfile=$this_dir/Dockerfile.$distro

echo "$this_dir/$dockerfile"

if [ ! -f "$dockerfile" ]; then
	echo "$distro: unsupported" >&2
	exit 1
fi

tag=my-docker-builder/$from

docker build -f $dockerfile -t $tag --build-arg FROM=$from $this_dir

if [ "$build_only" = 1 ]; then
	echo "Building '$tag' done"
	exit 0
fi

DOCKER_RUN_OPT=-it

for d in $mount_dirs
do
	# Mount useful directories if they exist in your home directory.
	# --volume=HOST_DIR:CONTAINER-DI
	if [ -d $HOME/$d ]; then
		DOCKER_RUN_OPT="$DOCKER_RUN_OPT --volume=$HOME/$d:/$d"
	fi
done

# This is needed for running 'strace' in a docker
DOCKER_RUN_OPT="$DOCKER_RUN_OPT --security-opt seccomp:unconfined"

docker run $DOCKER_RUN_OPT $tag /bin/bash
