#!/bin/sh

set -e

build_only=
user=foo
from=ubuntu

ARGS=$(getopt -o "bdf:u:" -l "build-only,debug,from:,user:" -n "$(basename $0)" -- "$@")

eval set -- $ARGS

while [ $# -gt 0 ]
do
	case $1 in
	-b|--build-only)
		build_only=1
		shift;;
	-d|--debug)
		set -x
		shift;;
	-f|--from)
		from=$2
		shift 2;;
	-u|--user)
		user=$2
		shift 2;;
	--)
		shift
		break;;
	esac
done

mount_dirs="ref tools"

distro=${from%:*}

# the directory path where this script is located
this_dir=$(dirname $(realpath $0))

dockerfile=$this_dir/Dockerfile.$distro

echo "$this_dir/$dockerfile"

if [ ! -f "$dockerfile" ]; then
	echo "$distro: unsupported" >&2
	exit 1
fi

tag=my-docker-builder/$from

docker build -f $dockerfile -t $tag --build-arg FROM=$from $this_dir

if [ "$build_only" = 1 ]; then
	echo "Building '$tag' done"
	exit 0
fi

DOCKER_RUN_OPT=-it

for d in $mount_dirs
do
	# Mount useful directories if they exist in your home directory.
	# --volume=HOST_DIR:CONTAINER-DI
	if [ -d $HOME/$d ]; then
		DOCKER_RUN_OPT="$DOCKER_RUN_OPT --volume=$HOME/$d:/$d"
	fi
done

# This is needed for running 'strace' in a docker
DOCKER_RUN_OPT="$DOCKER_RUN_OPT --security-opt seccomp:unconfined"

docker run $DOCKER_RUN_OPT $tag --user=$user --uid=$(id -u) --gid=$(id -g) -- /bin/bash
